### PR TITLE
Kaniz - Added Myself

### PR DESCRIPTION
**Pull request by Kaniz-Fatma**
Added my profile

### CODE REVIEW

**Review by prashantjagtap2909 — APPROVED** [review]

**Comment by prashantjagtap2909** [comment]
thank you

**Comment by Kaniz-Fatma** [comment]
can you label it as hacktoberfest-accepted .

**Comment by prashantjagtap2909** [comment]
done. Thanks for contribution....

**Comment by Kaniz-Fatma** [comment]
> done. Thanks for contribution....
 Without the label the pr doesn't count for hacktoberfest. Thank you for labelling it.

**Pull request merged**
